In [11]:
import numpy as np 

raw_data = np.arange(20)
print(f"raw data:{raw_data}")

raw data:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Task1:Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [12]:

task1 = raw_data.copy()
task1[3:9] *= -1

print(f"solution: {task1}")

solution: [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


Task2:Заменить максимальный элемент случайного массива на 0

In [13]:
task2 = raw_data.copy()

task2[task2.argmax()] = 0
print(f"Solution: {task2}")

Solution: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0]


 Task3: Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [14]:
import itertools

data = np.arange(4) 

# Calculate the square root dynamically
side = int(np.sqrt(data.size))

# Reshape into a square
matrix = data.reshape(side, side).copy()

print(matrix)
""" THIS IS NOT FINISHED, TOO COMPLICATED SOLUTION FOR A SIMPLE TASK
def something(array):
    rows, cols = array.shape
    matrix = []
    
    for i in range(rows):
        for j in range(cols):
            for k in range(rows):
                for l in range(cols):
                    if i == k or j == l:
                        continue
                    
                    tempRow = [array[i, j], array[k, l]]
                    
                    matrix.append(tempRow)
    return matrix
"""


def get_product(array):
    
    result = list(itertools.product(*array))
    return result


print(get_product(matrix))




[[0 1]
 [2 3]]
[(np.int64(0), np.int64(2)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(3))]


TASK4: Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [15]:
import numpy as np

A = np.array([[7, 3, 5], [1, 1, 7], [8, 0, 8],[9,5,3]]) # Sample from your output
B = np.array([[5, 8], [9, 5]])

final_results = []

for row in A:
    matches_B0 = np.intersect1d(row, B[0])
    matches_B1 = np.intersect1d(row, B[1])
    
    if matches_B0.size > 0 and matches_B1.size > 0:
        
        all_matches = np.union1d(matches_B0, matches_B1)
        
        if all_matches.size >= 2:
            final_results.append(row)

result = np.array(final_results)
print("Strict Matching Rows:")
print(result)

Strict Matching Rows:
[[9 5 3]]


TASK 5: Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [16]:
A = np.array([  [1, 1, 1],
                [1, 1, 7], 
                [8, 0, 8],
                [9, 5, 3],
                [2, 5, 3],
                [5, 5, 6],
                [2, 2, 2],
                [5, 5, 3],
                [1, 1, 1],
                [1, 1, 1],
                ]) # Sample from your output

masks = []

for i in range(len(A)):
    if (A[i] == A[i][0]).all():
        masks.append(False)
    else:
        masks.append(True)

print(A[masks])


[[1 1 7]
 [8 0 8]
 [9 5 3]
 [2 5 3]
 [5 5 6]
 [5 5 3]]


6. Дан двумерный массив. Удалить те строки, которые повторяются

In [17]:
B = np.array([[5, 8],[9, 5],[6, 8], [9, 5]])
unique_B = np.unique(B, axis=0)
print(unique_B)


[[5 8]
 [6 8]
 [9 5]]


Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).

Замечание 1. Можно считать, что все указанные объекты непустые (к примеру, в задаче 1 на диагонали матрицы есть ненулевые элементы).

Замечание 2. Для большинства задач решение занимает не больше 1-2 строк.

Задача 1: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.
Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [22]:
import math
Y = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

#sol1

sol1 = np.diag(Y)
rez = sol1[sol1 != 0].prod()
print(f"sol1:{rez}")

#sol2
rows,cols = Y.shape
changed = False
product = 1
if rows > cols:
    temp = rows
else:
    temp = cols
set = []
for i in range(temp-1):
    if X[i][i] != 0:
        product *= X[i][i]
        changed = True
        



print(f"sol2:{product}")

sol1:3
sol2:3


Задача 2: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.
Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
#sol1
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

def task2(x,y):

    if(len(x) != len(y)):
        print("NO")
        return

    a = b = {''}
    a.clear()
    b.clear()

    for number in y:
        b.add(number)

    for number in x:
        a.add(number)
        

    print(a == b)
    return a == b 

task2(x,y)
#sol2
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

print(np.array_equal(np.sort(x), np.sort(y)))



True
False


Задача 3: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
#sol1
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max = -99999

for i in range(len(x) - 1):
    if(x[i] == 0 and i < len(x) - 1):
        if x[i + 1] > max:
            max = x[i + 1]

print(max)

mask = (x[:-1] == 0)
candidates = x[1:][mask]

x = np.array(x) 

mask = (x[:-1] == 0)
candidates = x[1:][mask]

if candidates.size > 0:
    result = candidates.max()
else:
    result = None

print(result)


5
5


Задача 4: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.
Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
x = np.array([2, 2, 2, 3, 3, 3, 5]) 

currElem = None
amount = 0
elem_array = []
step_array = []


for number in x:
    if currElem != number:
        if(amount > 0):
            elem_array.append(currElem)
            step_array.append(amount)

        currElem = number
        amount = 1
    else:
        amount += 1

if(amount > 0):
    elem_array.append(currElem)
    step_array.append(amount)

list = [int(x) for x in elem_array]
print(list)
print(step_array)

#sol2

x = np.array([2, 2, 2, 3, 3, 3, 5])

# This one function replaces your entire loop
elements, counts = np.unique(x, return_counts=True)

# Convert to standard Python ints to avoid the "np.int64" labels
elem_list = elements.tolist()
step_list = counts.tolist()

print(elem_list) # [2, 3, 5]
print(step_list) # [3, 3, 1]


[2, 3, 5]
[3, 3, 1]


Задача 5: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
import numpy as np
from scipy.spatial.distance import cdist
import time

X = np.random.rand(500, 3)
Y = np.random.rand(400, 3)

# --- Method 1: NumPy Broadcasting ---
start_np = time.time()

# We change X from (500, 3) to (500, 1, 3)
# This forces NumPy to compare each X with every Y
dists_np = np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :])**2, axis=2))

end_np = time.time()

# --- Method 2: Scipy cdist ---
start_scipy = time.time()
dists_scipy = cdist(X, Y, metric='euclidean')
end_scipy = time.time()

print(f"NumPy time: {end_np - start_np:.5f}s")
print(f"Scipy time: {end_scipy - start_scipy:.5f}s")

print("Results match:", np.allclose(dists_np, dists_scipy))

NumPy time: 0.00677s
Scipy time: 0.00084s
Results match: True


Задача 6: CrunchieMunchies *
Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием CrunchieMunchies.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши СrunchieMunchies - самый здоровый выбор для потребителей

Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [62]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
print(calorie_stats)

[ 70. 120.  70.  50. 110. 110. 110. 130.  90.  90. 120. 110. 120. 110.
 110. 110. 100. 110. 110. 110. 100. 110. 100. 100. 110. 110. 100. 120.
 120. 110. 100. 110. 100. 110. 120. 120. 110. 110. 110. 140. 110. 100.
 110. 100. 150. 150. 160. 100. 120. 140.  90. 130. 120. 100.  50.  50.
 100. 100. 120. 100.  90. 110. 110.  80.  90.  90. 110. 110.  90. 110.
 140. 100. 110. 110. 100. 100. 110.]


В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

In [65]:
average_calories = np.mean(calorie_stats)
print(average_calories)

106.88311688311688


Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.
Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [67]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.
Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [68]:
median_calories = np.median(calorie_stats_sorted)
print(median_calories)

110.0


В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.
Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [74]:
nth_percentile = 0

# We check every percentile from 1 to 100
for i in range(1, 101):
    percentile_value = np.percentile(calorie_stats, i)
    if percentile_value > 60:
        nth_percentile = i
        break

print(f"The lowest percentile greater than 60 calories is: {nth_percentile}")

The lowest percentile greater than 60 calories is: 4


Task 6: Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.
Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [75]:
more_calories = np.mean(calorie_stats > 60) * 100

print(more_calories)

96.1038961038961
